language: go
go:
  - 1.4.2

branches:
  only:
    - master

before_install:
  - wget http://apache.claz.org/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -zxvf zookeeper*tar.gz
  - cd zookeeper*
  - cp conf/zoo_sample.cfg conf/zoo.cfg
  - cd bin
  - ./zkServer.sh start
  - cd ../..

script:
  - go build ./...
  - go fmt ./...
  - go get golang.org/x/tools/cmd/vet
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...

